### ISSUE TITLE
No vgl_entrypoint.sh found

### ISSUE THREAD

**Issue by ChangyaoTian** [CraftJarvis/MineStudio#1]
Hello, the url of [vgl_entrypoint.sh](https://craftjarvis.github.io/MineStudio/overview/installation.html#) is not avaliable, could you provide it? Thanks~

**Comment by phython96** [comment]
thanks for pointing that out, I have uploaded the [script](https://github.com/CraftJarvis/MineStudio/blob/master/assets/vgl_entrypoint.sh).
